#! /bin/sh

exec envdir ./env sh -c '
	export JAVA_OPTS="${MAX_HEAP+"-Xmx$MAX_HEAP"} ${MIN_HEAP+"-Xms$MIN_HEAP"} $JAVA_OPTS"
	exec setuidgid $USER $JAVA_HOME/bin/java $JAVA_OPTS -XX:MaxPermGen=512m -jar ./root/minecraft_server.jar nogui
'
