#! /bin/sh

# exec 2>&1 \
exec envdir ./env sh -c '
        cd $MINECRAFT_HOME 
        exec setuidgid $USER screen -A -m -d -S minecraft $JAVA_HOME/bin/java -Xmx$MAX_HEAP -Xms$MIN_HEAP -XX:MaxPermSize=$PERM_GEN -server -jar ./minecraft_server.jar nogui
'
