#! /bin/sh

exec 2>&1 \
envdir ./env \
sh -c '
	export JAVA_OPTS="-server ${MAX_HEAP+"-Xmx$MAX_HEAP"} ${MIN_HEAP+"-Xms$MIN_HEAP"} $JAVA_OPTS"
	export JAVA="$JAVA_HOME/bin/java"

	cd ./root
	exec ${USER+"setuidgid ${USER}"} \
	$JAVA $JAVA_OPTS -jar ./root/minecraft_server.jar nogui
'
